### ISSUE TITLE
Discord?

### ISSUE THREAD

**Issue by Kongen8800** [plgonzalezrx8/NecroReloaded#12]
Can you make a Discord channel?
Makes it easier for people to help each other. Also you get more time to focus on developing.

**Comment by plgonzalezrx8** [comment]
https://discord.gg/J7U8u

**Comment by plgonzalezrx8** [comment]
Its brand new so it still empty, but that will be the place to go.

**Comment by Kongen8800** [comment]
Thanks. Might be an idea to put the link on frontpage :)
