### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by joehsmash** [plgonzalezrx8/NecroReloaded#19]
i see that some one already requested to have the 1000/2000 limits to be put in place, is it possible also to have an exp limit,also a shut off the system limit?

currently i have been running with out fail for the last week, with staying under 100k exp per day, between 50-75exp per day than i log off. 

would be nice if the system could do this automatically.

you know if its not a PITA

thanks for all your hard work

**Comment by Unentertained** [comment]
#10

**Comment by plgonzalezrx8** [comment]
Already submitted, working on it.
