### ISSUE TITLE
Link to download?

### ISSUE THREAD

**Issue by RobertoAltman** [plgonzalezrx8/NecroReloaded#6]
Is there any link with a client working version?

**Comment by plgonzalezrx8** [comment]
Right under releases

**Comment by plgonzalezrx8** [comment]
https://github.com/plgonzalezrx8/MagicPoGoBot/releases

**Comment by plgonzalezrx8** [comment]
Get the release.zip

**Comment by dillusi** [comment]
Keep up with the work, with necro is no more it is difficult to find another decent bots and I am always ready to give a beer for the effort too :+1:
