### ISSUE TITLE
something not sure about soft ban and suggestions of new features 

### ISSUE THREAD

**Issue by philip2705** [plgonzalezrx8/NecroReloaded#8]
I know that there is a soft ban cause by  catch 1000 Pokemons or looting 1000 pokestops up ,  i can open the bot hole day and aften the next day it always got soft banned and I need to wait 24 hours for unban , so I want u guys maybe can make a new features that can count the pokemons or pokestops that you looted or caught ,or the bot can stop looting or catching itselfs .
Sorry for my bad English. Thx so much.

**Comment by dbw-holic** [comment]
It's ironic as what everyone is striving to do here will ultimately become great help for Niantic to improve their algorithms for bot-cheating detection. Not against you @philip2705 . Just want to say what it really feels like.

**Comment by dillusi** [comment]
Well, it is good to bot and then stop for a while, and even with the 1000/2000 limit, they will still catch you eventually (who will play the game 24/7? lol)
